apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream/serving-core.yaml
- upstream/net-istio.yaml
- istio-authorization-policy.yaml
patchesStrategicMerge:
- patches/configmap-patch.yaml
- patches/namespace-injection.yaml
- patches/clusterrole-patch.yaml
- patches/service-labels.yaml
patches:
- path: patches/sidecar-injection.yaml
  target:
    kind: Deployment
patchesJson6902:
- path: patches/knative-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: activator
    namespace: knative-serving
- path: patches/knative-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: autoscaler
    namespace: knative-serving
- path: patches/knative-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: controller
    namespace: knative-serving
- path: patches/knative-deploy-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: webhook
    namespace: knative-serving
